highligher: pygments
permalink: "/:year/:month/:day/:title.html"
paginate: 20
paginate_path: "/posts/:num/"
gems:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
